events {}

http {

    server {
        listen 80;
        server_name mycoai.bandhuja.com *.mycoai.bandhuja.com;

        return 301 https://$host$request_uri;
    }


    server {
        listen 443 ssl;
        server_name mycoai.bandhuja.com *.mycoai.bandhuja.com;

        ssl_certificate
            /etc/letsencrypt/live/mycoai.bandhuja.com/fullchain.pem;

        ssl_certificate_key
            /etc/letsencrypt/live/mycoai.bandhuja.com/privkey.pem;


        location / {
            return 200 "Mushroom IoT Nginx is working\n";
        }
    }
}
